version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - api
    volumes:
      - ./client:/usr/kalah/client

  api:
    ports:
      - "8080:8080"
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/kalah/api
    networks:
      - kalah-backend

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    command: "redis-server --protected-mode no"
    networks:
      - kalah-backend
    ports:
      - "6379:6379"

networks:
  kalah-backend:
